name: Create Issues from TODOs

on:
  push:
    branches:
      - master

jobs:
  build:
    # Run on latest version of ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          # "ref" specifies the branch to check out.
          # "github.event.release.target_commitish" is a global variable and specifies the branch the release targeted
          ref: ${{ github.event.release.target_commitish }}
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        id: "todo"
