name: UI Demo Continuous Integration

on:
  push:
    paths:
      - 'apps/demo/**'

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install whole project dependencies
        run: yarn --frozen-lockfile
        working-directory: 'apps/demo'
      - name: build ferns-ui
        run : yarn build
        working-directory: 'packages/ui'
      - name: yarn lint
        run: yarn lint
        working-directory: 'apps/demo'